apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-canary-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: client
        track: canary
    spec:
      containers:
      - image: gcr.io/linear-pointer-95422/client_image:v3.0.0
        name: client-container-name
        livenessProbe:
        # an http probe
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        ports:
        - containerPort: 3000
          protocol: TCP
