apiVersion: v1
kind: ReplicationController
metadata:
  name: client-blue
spec:
  replicas: 6
  selector:
    name: client
    version: v2.0.1
  template:
    metadata:
      labels:
        name: client
        version: v2.0.1
    spec:
      containers:
      - image: gcr.io/linear-pointer-95422/client_image:v2.0.1
        name: client
        livenessProbe:
        # an http probe
          httpGet:
            path: /_status/healthz
            port: 3000
        ports:
        - containerPort: 3000
          protocol: TCP
