apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: client
        track: stable
    spec:
      containers:
      - image: gcr.io/k8s-sample-project/client_image:v2.0.1
        name: client-container-name
        livenessProbe:
        # an http probe
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        ports:
        - containerPort: 3000
          protocol: TCP
