apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: client-green
spec:
  replicas: 2
  selector:
    name: client
    version: v1.0.3
  template:
    metadata:
      labels:
        name: client
        version: v1.0.3
    spec:
      containers:
      - image: gcr.io/mythical-willow-91020/client_image:v1.0.3
        name: client
        ports:
        - containerPort: 80
          protocol: TCP
