apiVersion: v1
kind: Service
metadata:
  labels:
    name: client-service
  name: client-service
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: client
    # track: canary
  type: LoadBalancer
