apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: client
  name: client
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    name: client
  createExternalLoadBalancer: true
