# Delays initial writing of response by a second 20% of the time
- delay: 1000
  frequency: 0.2

# Returns a 404 30% of the time
- status: 404
  frequency: 0.0

# Write 10,000,000 garbage bytes 9% of the time
- garbage: 10
  frequency: 0.0
